version: 2.1

workflows:
  tf-partner_profile:
    when: << pipeline.parameters.tf-partner_profile >>
    jobs:
      - tf-test:
          target-env: "sand/dshah"
          appName   : "partner_profile"
          context: 
            - cicd-deployer-aws-user
      - tf-plan:
          target-env: "sand/dshah"
          appName   : "partner_profile"
          context: 
            - cicd-deployer-aws-user
          requires:
            - tf-test
      - tf-apply:
          target-env: "sand/dshah"
          appName   : "partner_profile"
          context: 
            - cicd-deployer-aws-user
          filters:
            branches:
              only: main
          requires:
            - tf-plan