repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-merge-conflict
        files: ^infrastructure/tf/
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    hooks:
    - id: terraform_docs
    - id: terraform_fmt
    - id: terraform_tflint
      files: ^infrastructure/tf/
