jobs:
  app_starter:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    executor:
      name: python/default
      tag: "3.8"
    parameters:
      target-env:
        type: string
      appName:
        type: string
      directory:
        type: string
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps: 
      - attach_workspace:
          at: /tmp/workspace
      - aws-cli/setup
      - start_lambda:
          target-env: <<parameters.target-env>>
          appName: <<parameters.appName>>
          directory: <<parameters.directory>>
      - notify_slack_error
      - completed_slack_notification