commands:

##### APP DEPLOY COMMANDS ######
  tag_commit:
    parameters:
      app:
        default: ""
        type: string
    steps:
      - run : bash commons/auto_tag.sh <<parameters.app>>

  build_app:
    parameters:
      appName:
        default: ""
        type: string
    steps:
      - run: |
                cd apps/<<parameters.appName>>
                echo Building the code in `pwd` with: `python -V` `pip -V` and `poetry -V`
                poetry build
                poetry run pip install --upgrade -t package dist/*.whl
  create_package:
    parameters:
      appName:
        default: ""
        type: string
    steps:
      - run: |
              cd apps/<<parameters.appName>>/package
              echo Zipping the code in `pwd`
              mkdir -p out
              zip -r out/<<parameters.appName>>.zip . -x '*.pyc'
  upload_artifacts:
    parameters: 
      from:
        type: string
        description: A local *directory* path to sync with S3
      to:
        type: string
        description: A URI to an S3 bucket, i.e. 's3://the-name-my-bucket'
    steps:
      - aws-s3/sync:
          aws-region: AWS_REGION
          from: <<parameters.from>>
          to:   <<parameters.to>>

  start_lambda:
    parameters:
      target-env:
        type: string
        default: ""
    steps:
      - run: |
            aws lambda update-function-code --function-name techno-core-<<parameters.target-env>>-api-handler --region ${AWS_REGION} --s3-bucket informed-techno-core-<<parameters.target-env>>-lambda-images --s3-key api_handler.zip

################################

##### APP LINTER & TESTER ######
  linting_and_metrics:
    parameters:
      appName:
        default: ""
        type: string
    steps:
        - run: |
                cd apps/<<parameters.appName>>
                poetry run flake8
  py_tests:
    parameters:
      appName:
        default: ""
        type: string
    steps:
        - run: |
                cd apps/<<parameters.appName>>/tests
                poetry run pytest -v
            
###################################

###### TERRAFORM DEPLOY #######

  tf-plan:
    parameters:
      appName:
        default: ""
        type: string
      target-env:
        default: ""
        type: string
    steps:
      - run:
          name: terraform init & plan
          command: |
            cd infrastructure/<<parameters.appName>>/<<parameters.target-env>>
            terraform init -input=false
            terraform plan -out tfapply -var-file terraform.tfvars
  tf-apply:
    parameters:
      appName:
        default: ""
        type: string
      target-env:
        default: ""
        type: string
    steps:
      - run:
          name: terraform
          command: |
            cd infrastructure/<<parameters.appName>>/<<parameters.target-env>>
            terraform apply -auto-approve tfapply