commands:
###############################
####### SHARED COMMANDS #######
###############################
  tag_commit:
    parameters:
      directory:
        default: ""
        type: string
    steps:
      - run : bash commons/scripts/auto_tag.sh <<parameters.directory>>
  upload_artifacts:
    parameters: 
      from:
        type: string
        description: A local *directory* path to sync with S3
      to:
        type: string
        description: A URI to an S3 bucket, i.e. 's3://the-name-my-bucket'
    steps:
      - aws-s3/sync:
          aws-region: AWS_REGION
          from: <<parameters.from>>
          to:   <<parameters.to>>
  create_versioned_assets:
    parameters:
      from:
        type: string
      to:
        type: string
    steps:
      - aws-s3/copy:
          aws-region: AWS_REGION
          from: <<parameters.from>>
          to  : <<parameters.to>>
  create_env_vars:
    steps:
      - run: 
          name: Save Version
          command: |
                mkdir -p tmp_workspace
                echo "export GIT_TAG=\"${GIT_TAG}\"" >> tmp_workspace/env_vars
  docker_push:
    parameters:
      appName:
        default: ""
        type: string
      ecrRepo:
        default: ""
        type: string
      target-env:
        default: ""
        type: string
    steps:
      - run:
          name: Docker Push
          command: |
            docker tag <<parameters.appName>>:latest <<parameters.ecrRepo>>/cicd:<<parameters.appName>>-<<parameters.target-env>>-latest
            docker push <<parameters.ecrRepo>>/cicd:<<parameters.appName>>-<<parameters.target-env>>-latest
            docker tag <<parameters.appName>>:latest <<parameters.ecrRepo>>/cicd:${GIT_TAG}
            docker push <<parameters.ecrRepo>>/cicd:${GIT_TAG}
  docker-install:
    steps:
      - run:
          name: Install Docker client
          command: apk add docker-cli
#######################################
##### PYTHON APP LINTER & TESTER ######
#######################################
  py_linters:
    parameters:
      directory:
        default: ""
        type: string
    steps:
        - run:
            name: Linters
            command: |
                cd apps/<<parameters.directory>>
                poetry run flake8
  py_tests:
    parameters:
      directory:
        default: ""
        type: string
    steps:
        - run:
            name: Pytests
            command: |
                cd apps/<<parameters.directory>>/tests
                poetry run pytest -v
#######################################
##### PYTHON APP DEPLOY COMMANDS ######
#######################################
  poetry_build:
    parameters:
      directory:
        default: ""
        type: string
    steps:
      - run: 
          name: Poetry Build
          command: |
                cd apps/<<parameters.directory>>
                echo Building the code in `pwd` with: `python -V` `pip -V` and `poetry -V`
                poetry export --with layer -f requirements.txt --output requirements.txt --without-hashes
                poetry build
                poetry run pip install -r requirements.txt --upgrade --only-binary :all: --target package dist/*.whl
  py_create_package:
    parameters:
      directory:
        default: ""
        type: string
    steps:
      - run:
          name: Create Package
          command: |
              cd apps/<<parameters.directory>>/package
              echo Zipping the code in `pwd`
              mkdir -p out
              zip -r out/latest.zip . -x '*.pyc'
################################
#### PYTHON CONTAINER BUILD ####
################################
  poetry_container_build:
    parameters:
      directory:
        default: ""
        type: string
    steps:
      - run: 
          name: Poetry Container Build
          command: |
                cd apps/<<parameters.directory>>
                echo Building the code in `pwd` with: `python -V` `pip -V` and `poetry -V`
                poetry export --only main,layer,docker -f requirements.txt --output requirements.txt --without-hashes
  py_docker_build:
    parameters:
      directory:
        default: ""
        type: string
      appName:
        default: ""
        type: string
      otelLayerArn:
        default: ""
        type: string
      ecrRepo:
        default: ""
        type: string
      py-executor:
        default: ""
        type: string
    steps:
      - run:
          name: Python Docker Build
          command: |
            cd apps/<<parameters.directory>>
            echo Building docker image for <<parameters.appName>>
            aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin <<parameters.ecrRepo>>
            DOCKER_BUILDKIT=1 docker build --platform linux/amd64 -t <<parameters.appName>>:latest --build-arg PYTHON_VERSION=<<parameters.py-executor>> --build-arg HANDLER=<<parameters.directory>>.handler.handler .
################################
##### RUBY CONTAINER BUILD #####
################################
  ruby_docker_build:
    parameters:
      directory:
        default: ""
        type: string
      appName:
        default: ""
        type: string
      ecrRepo:
        default: ""
        type: string
    steps:
      - run:
          name: Ruby Docker Build
          command: |
            cd apps/<<parameters.directory>>
            echo Building docker image for <<parameters.appName>>
            aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin <<parameters.ecrRepo>>
            DOCKER_BUILDKIT=1 docker build --platform linux/amd64 -t <<parameters.appName>>:latest .
################################
##### APP STARTER COMMANDS #####
################################
  start_lambda:
    parameters:
      target-env:
        type: string
      appName:
        type: string
      directory:
        type: string
    steps:
      - run:
          name: Initiating Lambda
          command: |
            source tmp_workspace/env_vars
            function_arn=$(aws lambda update-function-code --function-name techno-core-<<parameters.target-env>>-<<parameters.appName>> --region ${AWS_REGION} --s3-bucket iq-artifacts-cicd-uswest2 --s3-key <<parameters.target-env>>/<<parameters.directory>>/latest.zip | jq -r .FunctionArn)
            date=$( date +'%m/%d/%Y %H:%M:%S:%3N')
            aws lambda tag-resource --resource $function_arn --tags version=${GIT_TAG},time="$date" --region ${AWS_REGION} 
###################################
## PYTHON CONTAINER APP STARTER ##
###################################
  start_container_lambda:
    parameters:
      target-env:
        type: string
        default: ""
      appName:
        default: ""
        type: string
      ecrRepo:
        default: ""
        type: string
    steps:
      - run:
          name: Initiating Container Lambda
          command: |
            source tmp_workspace/env_vars
            function_arn=$(aws lambda update-function-code --function-name techno-core-<<parameters.target-env>>-<<parameters.appName>> --region ${AWS_REGION} --image-uri <<parameters.ecrRepo>>/cicd:<<parameters.appName>>-<<parameters.target-env>>-latest | jq -r .FunctionArn)
            date=$( date +'%m/%d/%Y %H:%M:%S:%3N')
            aws lambda tag-resource --resource $function_arn --tags version=${GIT_TAG},time="$date" --region ${AWS_REGION} 
####################################
#### RUBY APP TESTER AND LINTER ####
####################################
  ruby_install_packages:
    parameters:
      directory:
        default: ""
        type: string
    steps:
        - run:
            name: Install Ruby Package
            command: |
                cd apps/<<parameters.directory>>
                gem install bundler -v 2.2.32
  ruby_linters:
    parameters:
      directory:
        default: ""
        type: string
    steps:
        - run:
            name: Linters
            command: |
                cd apps/<<parameters.directory>>
                bundle exec rubocop           
  ruby_tests:
    parameters:
      directory:
        default: ""
        type: string
    steps:
        - run:
            name: Pytests
            command: |
                cd apps/<<parameters.directory>>
                bundle exec rspec
###########################
##### RUBY APP DEPLOY #####
###########################   
  bundle_build:
    parameters:
      directory:
        default: ""
        type: string
    steps:
      - run: 
          name: Bundle Build
          command: |
                cd apps/<<parameters.directory>>
                echo Building the code in `pwd` with: `ruby -v` and `bundler -v`
                bundle config set --local deployment 'true'
                bundle install
  ruby_create_package:
    parameters:
      directory:
        default: ""
        type: string
    steps:
      - run:
          name: Create Package
          command: |
              cd apps/<<parameters.directory>>
              echo Zipping the code in `pwd`
              apt-get update && apt-get install -y zip
              mkdir -p out
              zip -r out/latest.zip .  
########################################
##### ARTIFACT PROMOTION COMMANDS ######
########################################
  artifact_promotion:
    parameters:
      from:
        type: string
      to:
        type: string
    steps:
      - aws-s3/copy:
          aws-region: AWS_REGION
          from: <<parameters.from>>
          to  : <<parameters.to>> 
  version_update:
    parameters:
      version:
        default: ""
        type: string
      target-env:
        default: ""
        type: string
    steps:
      - run:
          name: Version Update
          command: bash commons/scripts/version_update.sh <<parameters.version>> <<parameters.target-env>>
########################################
##### CONTAINER PROMOTION COMMANDS #####
######################################## 
  container_promotion:
    parameters:
      version:
        default: ""
        type: string
      target-env:
        default: ""
        type: string
      appName:
        default: ""
        type: string
    steps:
      - run:
          name: Container Promotion
          command: |
            MANIFEST=$(aws ecr batch-get-image --repository-name cicd --image-ids imageTag=<<parameters.version>> --output json --region us-west-2 | jq --raw-output --join-output '.images[0].imageManifest')
            aws ecr put-image --repository-name cicd --region us-west-2 --image-tag <<parameters.appName>>-<<parameters.target-env>>-latest --image-manifest "$MANIFEST"
###########################
######## SECURITY #########
###########################
  snyk_sca:
    parameters:
      directory:
        default: ""
        type: string
      snyk_token:
        default: ""
        type: string
    steps: 
      - run:
          name: "Snyk test"
          command: |
            n=0
            until [ "$n" -ge 5 ]
            do
                curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
                chmod +x snyk
                sudo mv ./snyk /usr/local/bin/
                snyk auth <<parameters.snyk_token>>
                cd apps/<<parameters.directory>>
                snyk test --command=python3 --fail-on=all || true
                break
                echo -e "\nCurl command failed. Retrying again...\n"
                n=$((n+1)) 
                sleep 1
            done
  snyk_sast:
    parameters:
      directory:
        default: ""
        type: string
      snyk_token:
        default: ""
        type: string
    steps: 
      - run:
          name: "Snyk code test"
          command: |
            n=0
            until [ "$n" -ge 5 ]
            do
                curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
                chmod +x snyk
                sudo mv ./snyk /usr/local/bin/
                snyk auth <<parameters.snyk_token>>
                cd apps/<<parameters.directory>>
                snyk code test || true
                break
                echo -e "\nCurl command failed. Retrying again...\n"
                n=$((n+1)) 
                sleep 1
            done
  snyk_iac:
    parameters:
      target-env:
        type: string
      appName:
        type: string
      snyk_token:
        default: ""
        type: string
    steps: 
      - run:
          name: "Install: Snyk & Terraform"
          command: |
            wget https://static.snyk.io/cli/latest/snyk-linux -O snyk
            chmod +x snyk
            sudo mv snyk /usr/local/bin
            snyk auth <<parameters.snyk_token>>
            wget https://releases.hashicorp.com/terraform/1.2.7/terraform_1.2.7_linux_amd64.zip -O terraform.zip
            sudo unzip terraform.zip -d /usr/local/bin/
      - run:
          name: "Test: Snyk iac"
          command: |
            echo "Executing Snyk tests for infrastructure/tf/<<parameters.appName>>/<<parameters.target-env>>..."
            terraform -chdir=infrastructure/tf/<<parameters.appName>>/<<parameters.target-env>> init -input=false
            terraform -chdir=infrastructure/tf/<<parameters.appName>>/<<parameters.target-env>> plan -input=false -out=tf-plan.out
            cd infrastructure/tf/<<parameters.appName>>/<<parameters.target-env>>; 
            terraform show -json tf-plan.out | jq '.' > tf-plan.json
            snyk iac test tf-plan.json --severity-threshold=high --report || true
################################
###### TERRAFORM TEST ##########
################################

###############################
###### TERRAFORM DEPLOY #######
###############################

################################
###### Push Notifications ######
################################
  start_slack_notification:
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*** Starting Deployment for Techno-core ***",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

  completed_slack_notification:
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*** Deployment for Techno-core Completed ***",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          mentions: '@dow-platform'
          template: basic_fail_1

  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          mentions: '@dow-platform'
          template: basic_success_1
#############################
###### Gather metrics #######
#############################