parameters:
  run-api_handler:
    type: boolean
    default: false
  run-api_handler-prod:
    type: boolean
    default: false
  run-api_handler-dev-api:
    type: boolean
    default: false
  run-api_handler-qa:
    type: boolean
    default: false
### Partner Profile ###
  run-partner_profile:
    type: boolean
    default: false
  run-partner_profile-prod:
    type: boolean
    default: false
  run-partner_profile-qa:
    type: boolean
    default: false  
  run-partner_profile-dev-api:
    type: boolean
    default: false
### Response Handler ###
  run-response_handler:
    type: boolean
    default: false
  run-response_handler-prod:
    type: boolean
    default: false
  run-response_handler-dev-api:
    type: boolean
    default: false
  run-response_handler-qa:
    type: boolean
    default: false
### Other param ### 
  version:
    type: string
    default: ""
  api_call:
    type: boolean
    default: false
  tf-version:
    type: string
    default: "1.2.7"
### TF Params ###
  tf-api_handler:
    type: boolean
    default: false
  tf-partner_profile:
    type: boolean
    default: false
  tf-response_handler:
    type: boolean
    default: false