jobs:
  tf-plan:
    parameters:
      target-env:
        type: string
      appName:
        type: string
    executor:
      name: terraform/default
      tag: <<pipeline.parameters.tf-version>>
    steps:
      - attach_workspace:
          at: .
      - terraform/plan:
          path: infrastructure/tf/<<parameters.appName>>/<<parameters.target-env>>
      - persist_to_workspace:
          root: .
          paths:
            - .