jobs:
  plan-apply:
    executor: terraform
    parameters:
      target-env:
        type: string
      appName:
        type: string
    steps:
      - attach_workspace:
          at: /root/.aws
      - tf-plan:
          appName: <<parameters.appName>>
          target-env: <<parameters.target-env>>
      - tf-apply:
          appName: <<parameters.appName>>
          target-env: <<parameters.target-env>>