executors:
  default:
    working_directory: infrastructure/
    docker:
      - image: hashicorp/terraform:1.2.7

jobs:
  init:
    parameters:
      target-env:
        type: string
      appName:
        type: string
    executor: default
    steps:
      - checkout
      - terraform/init:
          path: <<parameters.appName>>/<<parameters.target-env>>
      - terraform/fmt:
          path: <<parameters.appName>>/<<parameters.target-env>>
      - terraform/validate:
          path: <<parameters.appName>>/<<parameters.target-env>>
