jobs:
  plan-apply:
    working_directory: /tmp/project
    parameters:
      target-env:
        type: string
      appName:
        type: string
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - tf-plan:
          appName: <<parameters.appName>>
          target-env: <<parameters.target-env>>
      - tf-apply:
          appName: <<parameters.appName>>
          target-env: <<parameters.target-env>>
