jobs:
  tf-test:
    parameters:
      appName:
        type: string
      target-env:
        type: string
    executor:
      name: terraform/default
      tag: 1.2.7
    steps:
      - terraform/fmt:
          checkout: true
          path: infrastructure/<<parameters.appName>>/<<parameters.target-env>>
          recursive: true
      - terraform/validate:
          checkout: true
          path: infrastructure/<<parameters.appName>>/<<parameters.target-env>>
          tag: << pipeline.parameters.tf-version >>
      - persist_to_workspace:
          root: .
          paths:
            - .