jobs:
  tf-apply:
    parameters:
      target-env:
        type: string
      appName:
        type: string
    executor:
      name: terraform/default
      tag: <<pipeline.parameters.tf-version>>
    steps:
      - attach_workspace:
          at: .
      - debug_mode_on
      - terraform/apply:
          path: infrastructure/tf/<<parameters.appName>>/<<parameters.target-env>>