jobs:
  tf-test:
    parameters:
      appName:
        type: string
      target-env:
        type: string
    executor:
      name: terraform/default
      tag: <<pipeline.parameters.tf-version>>
    parallelism: 2
    steps:
      - terraform/fmt:
          path: infrastructure/tf/<<parameters.appName>>/<<parameters.target-env>>
          recursive: true
      - terraform/validate:
          path: infrastructure/tf/<<parameters.appName>>/<<parameters.target-env>>
      - persist_to_workspace:
          root: .
          paths:
            - .