executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.2.7

jobs:
  init:
    executor: terraform
    parameters:
      target-env:
        type: string
      appName:
        type: string
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: cicd
      - tf-init:
          appName: <<parameters.appName>>
          target-env: <<parameters.target-env>>
      - persist_to_workspace:
          root: .
          paths:
            - .