executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.2.7

jobs:
  plan-apply:
    executor: terraform
    working_directory: /tmp/project
    parameters:
      target-env:
        type: string
      appName:
        type: string
      userContext:
        type: string
    steps:
      - checkout
      - tf-init:
          context: <<parameters.userContext>>
          appName: <<parameters.appName>>
          target-env: <<parameters.target-env>>
      - tf-plan:
          appName: <<parameters.appName>>
          target-env: <<parameters.target-env>>
      - tf-apply:
          appName: <<parameters.appName>>
          target-env: <<parameters.target-env>>
