 
jobs:
  py_app_testing:
    executor:
      name: python/default
      tag: "3.7"
    parameters:
      directory:
        type: string
    parallelism: 2
    steps:
      - checkout
      - python/install-packages:
          app-dir: ~/project/apps/<<parameters.directory>>
          pkg-manager: poetry
      - py_linters:
          directory: <<parameters.directory>>
      - py_tests:
          directory: <<parameters.directory>>
      - notify_slack_error