jobs:
  py_app_builder:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    executor:
      name: python/default
      tag: "3.8"
    parameters:
      target-env:
        type: string
      directory:
        type: string
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - start_slack_notification
      - checkout
      - tag_commit:
          directory: <<parameters.directory>>
      - python/install-packages:
          app-dir: ~/project/apps/<<parameters.directory>>
          pkg-manager: poetry
      - poetry_build:
          directory: <<parameters.directory>>
      - py_create_package:
          directory: <<parameters.directory>>
      - upload_artifacts:
          from: apps/<<parameters.directory>>/package/out
          to: s3://iq-artifacts-cicd-uswest2/<<parameters.target-env>>/<<parameters.directory>>
      - create_versioned_assets:
          from: s3://iq-artifacts-cicd-uswest2/<<parameters.target-env>>/<<parameters.directory>>/latest.zip
          to: s3://iq-artifacts-cicd-uswest2/<<parameters.target-env>>/<<parameters.directory>>/${GIT_TAG}.zip
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - /tmp/workspace/env_vars
      - notify_slack_error