jobs:
  ruby_app_builder:
    docker:
      - image: ruby:2.7
    parameters:
      target-env:
        type: string
      directory:
        type: string
    steps:
      - start_slack_notification
      - checkout
      - tag_commit:
          directory: <<parameters.directory>>
      - bundle_build:
          directory: <<parameters.directory>>
      - ruby_create_package:
          directory: <<parameters.directory>>
      - upload_artifacts:
          from: apps/<<parameters.directory>>/out
          to: s3://iq-artifacts-cicd-uswest2/<<parameters.target-env>>/<<parameters.directory>>
      - create_versioned_assets:
          from: s3://iq-artifacts-cicd-uswest2/<<parameters.target-env>>/<<parameters.directory>>/latest.zip
          to: s3://iq-artifacts-cicd-uswest2/<<parameters.target-env>>/<<parameters.directory>>/${GIT_TAG}.zip
      - notify_slack_error