jobs:
  ruby_app_builder:
    docker:
      - image: ruby:2.7
    parameters:
      target-env:
        type: string
      appName:
        type: string
    steps:
      - start_slack_notification
      - checkout
      - tag_commit:
          appName: <<parameters.appName>>
      - bundle_build:
          appName: <<parameters.appName>>
      - ruby_create_package:
          appName: <<parameters.appName>>
      - upload_artifacts:
          from: apps/<<parameters.appName>>/out
          to: s3://iq-artifacts-cicd-uswest2/<<parameters.target-env>>/<<parameters.appName>>
      - create_versioned_assets:
          from: s3://iq-artifacts-cicd-uswest2/<<parameters.target-env>>/<<parameters.appName>>/latest.zip
          to: s3://iq-artifacts-cicd-uswest2/<<parameters.target-env>>/<<parameters.appName>>/${GIT_TAG}.zip
      - notify_slack_error