 
jobs:
  ruby_app_testing:
    docker:
      - image: ruby:3.0.3
    parameters:
      directory:
        type: string
    parallelism: 2
    steps:
      - checkout
      - ruby_install_packages:
          directory: <<parameters.directory>>
      - bundle_build:
          directory: <<parameters.directory>>
      - ruby_linters:
          directory: <<parameters.directory>>
      - ruby_tests:
          directory: <<parameters.directory>>
      - notify_slack_error