jobs:
  security_sca:
    executor:
      name: python/default
      tag: "3.8"
    parameters:
      appName:
        type: string
    parallelism: 2
    steps:
      - checkout
      - snyk_sca:
          appName: <<parameters.appName>>
          snyk_token: ${SNYK_TOKEN}
      - notify_slack_error
  security_sast:
    executor:
      name: python/default
      tag: "3.8"
    parameters:
      appName:
        type: string
    parallelism: 2
    steps:
      - checkout
      - snyk_sast:
          appName: <<parameters.appName>>
          snyk_token: ${SNYK_TOKEN}
      - notify_slack_error