jobs:
  security_sca:
    working_directory: ~/project/apps/<<parameters.appName>>
    executor:
      name: python/default
      tag: "3.8"
    parameters:
      appName:
        type: string
    parallelism: 2
    steps:
      - checkout
      - change_dir:
          appName: <<parameters.appName>>
      - python/install-packages:
          pkg-manager: poetry
      - snyk/scan