version: 2.1

jobs:
  api_handler_app_deploy:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    executor:
      name: python/default
      tag: "3.8"
    parameters:
      target-env:
        type: string
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Build the Api Handler
          command: |
                echo `pwd`
      - tag_commit:
          app: api_handler
      - python/install-packages:
          app-dir: ~/project/api_handler
          pkg-manager: poetry
      - build_app:
          directory: api_handler
      - create_package:
          directory: api_handler/package
      - upload_artifacts:
          from: api_handler/package/out
          to: s3://informed-techno-core-<<parameters.target-env>>-lambda-images
      - start_lambda:
          target-env: <<parameters.target-env>>

workflows:
  api_handler_run:
    when: << pipeline.parameters.run-api_handler >>
    jobs:
      - api_handler_app_deploy:
          target-env: "dshah"
          context: 
            - dshah-aws-user-creds