version: 2.1

workflows:

  tf-app-demo-page-ocr-dev_PR:
    when: 
      and:
        - equal: [ true, << pipeline.parameters.tf-app-demo-page-ocr-dev >> ]
        - equal: [ false, << pipeline.parameters.api_call>> ]
        - not:
            equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - security_iac:
          name      : security-iac-image-app-demo-page-ocr-dev
          target-env: "dev"
          appName   : "app-demo-page-ocr"
          context   :
            - snyk-token
            - cicd-platform-slack-creds
            - cicd-aws-user-creds
      - tf-test:
          name: tf-tester-app-demo-page-ocr
          target-env: "dev"
          appName   : "app-demo-page-ocr"
          context: 
            - cicd-deployer-aws-user

  tf-app-demo-page-ocr-dev:
    when:
      and:
        - equal: [false, << pipeline.parameters.run-app_demo_page_ocr >>]
        - equal: [true, << pipeline.parameters.tf-app-demo-page-ocr-dev >>]
        - equal: [main, << pipeline.git.branch >>]
        - equal: [false, << pipeline.parameters.api_call>>]
    jobs:
      - tf-test:
          name: tf-tester-app-demo-page-ocr
          target-env: "dev"
          appName   : "app-demo-page-ocr"
          context: 
            - cicd-deployer-aws-user
      - tf-plan:
          name: tf-plan-app-demo-page-ocr
          target-env: "dev"
          appName   : "app-demo-page-ocr"
          context: 
            - cicd-deployer-aws-user
          requires:
            - tf-tester-app-demo-page-ocr
      - tf-apply:
          name: tf-apply-app-demo-page-ocr
          target-env: "dev"
          appName   : "app-demo-page-ocr"
          context: 
            - cicd-deployer-aws-user
          requires:
            - tf-plan-app-demo-page-ocr