version: 2.1

workflows:

  tf-app_demo-dev_PR:
    when: 
      and:
        - equal: [ true, << pipeline.parameters.tf-app-demo-dev >> ]
        - equal: [ false, << pipeline.parameters.api_call>> ]
        - not:
            equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - security_iac:
          name      : security-iac-api_handler-dev
          target-env: "dev"
          appName   : "app-demo"
          context   :
            - snyk-token
            - cicd-platform-slack-creds
            - cicd-aws-user-creds
      - tf-test:
          name: tf-tester-app-demo
          target-env: "dev"
          appName   : "app-demo"
          context: 
            - cicd-deployer-aws-user

  tf-app-demo-dev:
    when:
      and:
        - equal: [ true, << pipeline.parameters.tf-app-demo-dev >> ]
        - equal: [ false, << pipeline.parameters.run-app_demo >> ]
        - equal: [ main, << pipeline.git.branch >> ]
        - equal: [ false, << pipeline.parameters.api_call>> ] 
    jobs:
      - tf-test:
          name: tf-tester-app-demo
          target-env: "dev"
          appName   : "app-demo"
          context: 
            - cicd-deployer-aws-user
      - tf-plan:
          name: tf-plan-app-demo
          target-env: "dev"
          appName   : "app-demo"
          context: 
            - cicd-deployer-aws-user
          requires:
            - tf-tester-app-demo
      - tf-apply:
          name: tf-apply-app-demo
          target-env: "dev"
          appName   : "app-demo"
          context: 
            - cicd-deployer-aws-user
          requires:
            - tf-plan-app-demo