version: 2.1

workflows:
  app_demo_page_ocr_PR:
    when:
      and:
        - equal: [true, << pipeline.parameters.run-app_demo_page_ocr >>]
        - equal: [false, << pipeline.parameters.api_call>>]
        - not:
            equal: [main, << pipeline.git.branch >>]
    jobs:
      - py_app_testing:
          name: app-tester-app_demo_page_ocr
          directory: "app_demo_page_ocr"
          py-executor: "3.7"
          context:
            - dev-aws-user-creds
            - cicd-platform-slack-creds
      - security_sca:
          name: security-sca-app_demo_page_ocr
          directory: "app_demo_page_ocr"
          context:
            - snyk-token
            - cicd-platform-slack-creds
      - security_sast:
          name: security-sast-app_demo_page_ocr
          directory: "app_demo_page_ocr"
          context:
            - snyk-token
            - cicd-platform-slack-creds

  app_demo_page_ocr:
    when:
      and:
        - equal: [true, << pipeline.parameters.run-app_demo_page_ocr >>]
        - equal: [false, << pipeline.parameters.tf-app-demo-page-ocr-dev >>]
        - equal: [main, << pipeline.git.branch >>]
        - equal: [false, << pipeline.parameters.api_call>>]
    jobs:
      - py_container_builder:
          name: app-builder-app_demo_page_ocr
          target-env: "dev"
          appName: "app-demo-page-ocr"
          directory: "app_demo_page_ocr"
          py-executor: "3.9"
          context:
            - cicd-aws-user-creds
            - cicd-platform-slack-creds
      - container_starter:
          name: app-starter-app_demo_page_ocr
          target-env: "dev"
          appName: "app-demo-page-ocr"
          directory: "app_demo_page_ocr"
          context:
            - dev-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - app-builder-app_demo_page_ocr

  app_demo_page_ocr_tf:
    when:
      and:
        - equal: [true, << pipeline.parameters.run-app_demo_page_ocr >>]
        - equal: [true, << pipeline.parameters.tf-app-demo-page-ocr-dev >>]
        - equal: [main, << pipeline.git.branch >>]
        - equal: [false, << pipeline.parameters.api_call>>]
    jobs:
      - py_app_testing:
          name: app-tester-app_demo_page_ocr
          directory: "app_demo_page_ocr"
          context:
            - dev-aws-user-creds
            - cicd-platform-slack-creds
      - py_app_builder:
          name: app-builder-app_demo_page_ocr
          target-env: "dev"
          directory: "app_demo_page_ocr"
          context:
            - cicd-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - app-tester-app_demo_page_ocr
      - tf-test:
          name: tf-tester-app-demo-page-ocr
          target-env: "dev"
          appName: "app-demo-page-ocr"
          context:
            - cicd-deployer-aws-user
          requires:
            - app-builder-app_demo_page_ocr
      - tf-plan:
          name: tf-plan-app-demo-page-ocr
          target-env: "dev"
          appName: "app-demo-page-ocr"
          context:
            - cicd-deployer-aws-user
          requires:
            - tf-tester-app-demo-page-ocr
      - tf-apply:
          name: tf-apply-app-demo-page-ocr
          target-env: "dev"
          appName: "app-demo-page-ocr"
          context:
            - cicd-deployer-aws-user
          requires:
            - tf-plan-app-demo-page-ocr
      - app_starter:
          name: app-starter-app_demo_page_ocr
          target-env: "dev"
          appName: "app-demo-page-ocr"
          directory: "app_demo_page_ocr"
          context:
            - dev-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - tf-apply-app-demo-page-ocr
