version: 2.1

workflows:
  tf-api_handler:
    when: << pipeline.parameters.tf-api_handler >>
    jobs:
      - terraform-format:
          iacPath: infrastructure/api_handler/sand/dshah
      - terraform-validate:
          iacPath: infrastructure/api_handler/sand/dshah
          context:
            - cicd-deployer-aws-user
          requires:
            - terraform-format
      - terraform-plan:
          iacPath: infrastructure/api_handler/sand/dshah
          context:
            - cicd-deployer-aws-user
          requires:
            - terraform-validate
      # - approve-terraform-apply:
      #     type: approval
      #     filters:
      #       branches:
      #         only: main
      #     requires:
      #       - terraform-plan