version: 2.1

workflows:

  tf-api_handler_PR:
    when: 
      and:
        - equal: [ true, << pipeline.parameters.tf-api_handler >> ]
        - equal: [ false, << pipeline.parameters.api_call>> ]
        - not:
            equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - tf-test:
          name: tf-tester-api_handler
          target-env: "sand/dshah"
          appName   : "api_handler"
          context: 
            - cicd-deployer-aws-user

  tf-api_handler:
    when:
      and:
        - equal: [ true, << pipeline.parameters.tf-api_handler >> ]
        - equal: [ main, << pipeline.git.branch >> ]
        - equal: [ false, << pipeline.parameters.api_call>> ] 
    jobs:
      - tf-test:
          name: tf-tester-api_handler
          target-env: "sand/dshah"
          appName   : "api_handler"
          context: 
            - cicd-deployer-aws-user
      - tf-plan:
          name: tf-plan-api_handler
          target-env: "sand/dshah"
          appName   : "api_handler"
          context: 
            - cicd-deployer-aws-user
          requires:
            - tf-tester-api_handler
      - tf-apply:
          name: tf-apply-api_handler
          target-env: "sand/dshah"
          appName   : "api_handler"
          context: 
            - cicd-deployer-aws-user
          requires:
            - tf-plan-api_handler