version: 2.1

workflows:

  tf-api_handler_PR:
    when: 
      - and:
        - equal: [ true, << pipeline.parameters.tf-api_handler >> ]
        - equal: [ false, << pipeline.parameters.api_call>> ]
        - not:
            equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - tf-test:
          target-env: "sand/dshah"
          appName   : "api_handler"
          context: 
            - cicd-deployer-aws-user

  tf-api_handler:
    when:
      - and:
        - equal: [ true, << pipeline.parameters.tf-api_handler >> ]
        - equal: [ main, << pipeline.git.branch >> ]
        - equal: [ false, << pipeline.parameters.api_call>> ] 
    jobs:
      - tf-test:
          target-env: "sand/dshah"
          appName   : "api_handler"
          context: 
            - cicd-deployer-aws-user
      - tf-plan:
          target-env: "sand/dshah"
          appName   : "api_handler"
          context: 
            - cicd-deployer-aws-user
          requires:
            - tf-test
      - tf-apply:
          target-env: "sand/dshah"
          appName   : "api_handler"
          context: 
            - cicd-deployer-aws-user
          filters:
            branches:
              only: main
          requires:
            - tf-plan