version: 2.1

workflows:
  api_handler_tf:
    when: << pipeline.parameters.tf-dev_api_handler >>
    jobs:
      - init:
          target-env: "sand/dshah"
          appName   : "partner_profile"
          context: 
            - cicd-aws-user-creds
      - plan-apply:
          target-env: "sand/dshah"
          appName   : "partner_profile"
          context: 
            - dshah-aws-user-creds
          requires:
            - init
