version: 2.1

workflows:
  api_handler_tf:
    when: << pipeline.parameters.tf-dev_api_handler >>
    jobs:
      - plan-apply:
          target-env: "sand/dshah"
          appName   : "api_handler"
          context: 
            - cicd-aws-user-creds
