# Set an environemnt variable 'OPENTELEMETRY_COLLECTOR_CONFIG_FILE' to '/var/task/app/config/rberger_otel_collector.yaml'

receivers:
  otlp:
    protocols:
      http:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      x-honeycomb-team: "Qf0n7UBOs2sG3DL7SA8CDD"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, logging]
