version: 2.1

workflows:

  tf-app-demo-verification-service-dev_PR:
    when: 
      and:
        - equal: [ true, << pipeline.parameters.tf-app-demo-verification-service-dev >> ]
        - equal: [ false, << pipeline.parameters.api_call>> ]
        - not:
            equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - security_iac:
          name      : security-iac-image-app-demo-verification-service-dev
          target-env: "dev"
          appName   : "app-demo-verification-service"
          context   :
            - snyk-token
            - cicd-platform-slack-creds
            - cicd-aws-user-creds
      - tf-test:
          name: tf-tester-app-demo-verification-service
          target-env: "dev"
          appName   : "app-demo-verification-service"
          context: 
            - cicd-deployer-aws-user

  tf-app-demo-verification-service-dev:
    when:
      and:
        - equal: [false, << pipeline.parameters.run-app_demo_verification_service >>]
        - equal: [true, << pipeline.parameters.tf-app-demo-verification-service-dev >>]
        - equal: [main, << pipeline.git.branch >>]
        - equal: [false, << pipeline.parameters.api_call>>]
    jobs:
      - tf-test:
          name: tf-tester-app-demo-verification-service
          target-env: "dev"
          appName   : "app-demo-verification-service"
          context: 
            - cicd-deployer-aws-user
      - tf-plan:
          name: tf-plan-app-demo-verification-service
          target-env: "dev"
          appName   : "app-demo-verification-service"
          context: 
            - cicd-deployer-aws-user
          requires:
            - tf-tester-app-demo-verification-service
      - tf-apply:
          name: tf-apply-app-demo-verification-service
          target-env: "dev"
          appName   : "app-demo-verification-service"
          context: 
            - cicd-deployer-aws-user
          requires:
            - tf-plan-app-demo-verification-service