version: 2.1

workflows:
  app_demo-dev-api:
    when:
      and:
        - matches:
            pattern: /^[a-zA-Z0-9_]+-\d+\.\d+\.\d-[rc\d]+$/
            value: << pipeline.parameters.version >>
        - equal: [ true, << pipeline.parameters.run-app_demo-dev-api >> ]
        - equal: [ true, << pipeline.parameters.api_call>> ]
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - artifact_promoter:
          name: artifact-promoter-app_demo-dev-api
          target-env: "dev-api"
          appName   : "app-demo"
          directory : "app_demo"
          version: << pipeline.parameters.version >>
          context:
            - cicd-aws-user-creds
            - cicd-platform-slack-creds
      - tf-test:
          name: tf-tester-app_demo-dev-api
          target-env: "dev-api"
          appName   : "app-demo"
          context:
            - cicd-deployer-aws-user
          requires:
            - artifact-promoter-app_demo-dev-api
      - tf-plan:
          name: tf-plan-app_demo-dev-api
          target-env: "dev-api"
          appName   : "app-demo"
          context:
            - cicd-deployer-aws-user
          requires:
            - tf-tester-app_demo-dev-api
      - tf-apply:
          name: tf-apply-app_demo-dev-api
          target-env: "dev-api"
          appName   : "app-demo"
          context:
            - cicd-deployer-aws-user
          requires:
            - tf-plan-app_demo-dev-api
      - app_starter:
          name: app-starter-app_demo-dev-api
          target-env: "dev-api"
          appName   : "app-demo"
          directory : "app_demo"
          context:
            - dev-api-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - tf-apply-app_demo-dev-api
      # - slack/on-hold:
      #     mentions: '@dow-platform'
      #     context:
      #       - cicd-platform-slack-creds
      #     requires:
      #       - app-starter-for-dev
