version: 2.1

workflows:
  api_handler_run:
    when: << pipeline.parameters.run-api_handler >>
    jobs:
      - app_testing:
          appName   : "api_handler"
          context:
            - dshah-aws-user-creds
      - app_builder:
          target-env: "dshah"
          appName   : "api_handler"
          context: 
            - cicd-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - app_testing
      - app_starter:
          name: app-starter-for-prod
          target-env: "dshah"
          appName   : "api-handler"
          directory : "api_handler"
          context: 
            - dshah-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - app_builder
      - slack/on-hold:
          mentions: '@dow-platform'
          context: 
            - cicd-platform-slack-creds
          requires:
            - app-starter-for-prod
      - pause_workflow:
          type: approval
          requires:
            - slack/on-hold
      - app_starter:
          name: app-starter-for-dev
          target-env: "dev"
          appName   : "api-handler"
          directory : "api_handler"
          context: 
            - dev-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - pause_workflow

  api_handler_run-prod:
    jobs:
      - init:
          target-env: "sand/dshah"
          appName   : "api_handler"
          context: 
            - cicd-aws-user-creds
          filters:
            tags:
              only: opq
            branches:
              only: main
      - app_testing:
          appName   : "api_handler"
          context:
            - dshah-aws-user-creds
          filters:
            tags:
              only: opq
            branches:
              only: main
          requires:
            - init
      - app_builder:
          target-env: "dshah"
          appName   : "api_handler"
          context: 
            - cicd-aws-user-creds
            - cicd-platform-slack-creds
          filters:
            tags:
              only: opq
            branches:
              only: main
          requires:
            - app_testing
      - app_starter:
          name: app-starter-for-prod
          target-env: "dshah"
          appName   : "api-handler"
          directory : "api_handler"
          context: 
            - dshah-aws-user-creds
            - cicd-platform-slack-creds
          filters:
            tags:
              only: opq
            branches:
              only: main
          requires:
            - app_builder
      - slack/on-hold:
          mentions: '@dow-platform'
          context: 
            - cicd-platform-slack-creds
          filters:
            tags:
              only: opq
            branches:
              only: main
          requires:
            - app-starter-for-prod
      - pause_workflow:
          type: approval
          filters:
            tags:
              only: opq
            branches:
              only: main
          requires:
            - slack/on-hold
      - app_starter:
          name: app-starter-for-dev
          target-env: "dev"
          appName   : "api-handler"
          directory : "api_handler"
          context: 
            - dev-aws-user-creds
            - cicd-platform-slack-creds
          filters:
            tags:
              only: opq
            branches:
              only: main
          requires:
            - pause_workflow