version: 2.1

workflows:
  api_handler_run:
    when: 
      and:
        - equal: [ true, << pipeline.parameters.run-api_handler >> ]
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - app_testing:
          appName   : "api_handler"
          context:
            - dshah-aws-user-creds
            - cicd-platform-slack-creds
      - app_builder:
          target-env: "dshah"
          appName   : "api_handler"
          context: 
            - cicd-aws-user-creds
          requires:
            - app_testing
      - app_starter:
          name: app-starter-for-staging
          target-env: "dshah"
          appName   : "api-handler"
          directory : "api_handler"
          context: 
            - dshah-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - app_builder
      - slack/on-hold:
          mentions: '@dow-platform'
          context: 
            - cicd-platform-slack-creds
          requires:
            - app-starter-for-staging
      - pause_workflow:
          type: approval
          requires:
            - slack/on-hold
      - app_starter:
          name: app-starter-for-prod
          target-env: "dev"
          appName   : "api-handler"
          directory : "api_handler"
          context: 
            - dev-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - pause_workflow

  api_handler_run_PR:
    when: 
      and:
        - equal: [ true, << pipeline.parameters.run-api_handler >> ]
        - not:
            equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - app_testing:
          appName   : "api_handler"
          context:
            - dshah-aws-user-creds
            - cicd-platform-slack-creds