version: 2.1

workflows:
  api_handler_run_PR:
    when: 
      and:
        - equal: [ true, << pipeline.parameters.run-api_handler >> ]
        - equal: [ false, << pipeline.parameters.api_call>> ]
        - not:
            equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - app_testing:
          appName   : "api_handler"
          context:
            - dshah-aws-user-creds
            - cicd-platform-slack-creds

  api_handler_run:
    when: 
      and:
        - equal: [ true, << pipeline.parameters.run-api_handler >> ]
        - equal: [ main, << pipeline.git.branch >> ]
        - equal: [ false, << pipeline.parameters.api_call>> ]
    jobs:
      - app_testing:
          appName   : "api_handler"
          context:
            - dshah-aws-user-creds
            - cicd-platform-slack-creds
      - app_builder:
          target-env: "dshah"
          appName   : "api_handler"
          context: 
            - cicd-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - app_testing
      - app_starter:
          name: app-starter-for-dev
          target-env: "dshah"
          appName   : "api-handler"
          directory : "api_handler"
          context: 
            - dshah-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - app_builder