version: 2.1

workflows:
  api_handler-qa:
    when:
      and:
        - matches:
            pattern: /^[a-zA-Z0-9_]+-\d+\.\d+\.\d+-[rc\d]+$/
            value: << pipeline.parameters.version >>
        - equal: [ true, << pipeline.parameters.run-api_handler-qa >> ]
        - equal: [ true, << pipeline.parameters.api_call>> ]
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - artifact_promoter:
          name: artifact-promoter-api_handler-qa
          target-env: "qa"
          appName   : "api-handler"
          directory : "api_handler"
          version: << pipeline.parameters.version >>
          context:
            - cicd-aws-user-creds
            - cicd-platform-slack-creds
      - tf-test:
          name: tf-tester-api_handler-qa
          target-env: "qa"
          appName   : "api-handler"
          context:
            - cicd-deployer-aws-user
          requires:
            - artifact-promoter-api_handler-qa
      - tf-plan:
          name: tf-plan-api_handler-qa
          target-env: "qa"
          appName   : "api-handler"
          context:
            - cicd-deployer-aws-user
          requires:
            - tf-tester-api_handler-qa
      - tf-apply:
          name: tf-apply-api_handler-qa
          target-env: "qa"
          appName   : "api-handler"
          context:
            - cicd-deployer-aws-user
          requires:
            - tf-plan-api_handler-qa
            - security-iac-api_handler-qa
      - app_starter:
          name: app-starter-api_handler-qa
          target-env: "qa"
          appName   : "api-handler"
          directory : "api_handler"
          context:
            - qa-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - tf-apply-api_handler-qa
      # - slack/on-hold:
      #     mentions: '@dow-platform'
      #     context:
      #       - cicd-platform-slack-creds
      #     requires:
      #       - app-starter-for-qa