version: 2.1

workflows:
  api_handler_run:
    when: << pipeline.parameters.run-api_handler >>
    jobs:
      - app_testing:
          appName   : "api_handler"
          context:
            - dshah-aws-user-creds
      - app_builder:
          target-env: "dshah"
          appName   : "api_handler"
          context: 
            - cicd-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - app_testing
      - app_starter:
          target-env: "dshah"
          appName   : "api-handler"
          directory : "api_handler"
          context: 
            - dshah-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - app_builder
      - slack/on-hold:
          mentions: '@dow-platform'
          context: 
            - cicd-platform-slack-creds
          requires:
            - app_starter
      - pause_workflow:
          type: approval
          requires:
            - slack/on-hold
      - app_starter-qa:
          target-env: "dshah"
          appName   : "api-handler"
          directory : "api_handler"
          context: 
            - dshah-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - pause_workflow
