version: 2.1

workflows:
  response_handler_PR:
    when:
      and:
        - equal: [ true, << pipeline.parameters.run-response_handler >> ]
        - equal: [ false, << pipeline.parameters.api_call>> ]
        - not:
            equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - py_app_testing:
          name      : app-tester-response_handler
          directory   : "response_handler"
          context   :
            - dev-aws-user-creds
            - cicd-platform-slack-creds
      - security_sca:
          name      : security-sca-response_handler
          directory   : "response_handler"
          context   :
            - snyk-token
            - cicd-platform-slack-creds
      - security_sast:
          name      : security-sast-response_handler
          directory   : "response_handler"
          context   :
            - snyk-token
            - cicd-platform-slack-creds

  response_handler:
    when:
      and:
        - equal: [ true, << pipeline.parameters.run-response_handler >> ]
        - equal: [ main, << pipeline.git.branch >> ]
        - equal: [ false, << pipeline.parameters.api_call>> ]
    jobs:
      - py_app_testing:
          name: app-tester-response_handler
          directory   : "response_handler"
          context:
            - dev-aws-user-creds
            - cicd-platform-slack-creds
      - py_app_builder:
          name: app-builder-response_handler
          target-env: "dev"
          directory   : "response_handler"
          context:
            - cicd-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - app-tester-response_handler
      - app_starter:
          name: app-starter-response_handler
          target-env: "dev"
          appName   : "response-handler"
          directory : "response_handler"
          context:
            - dev-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - app-builder-response_handler
