from enum import Enum


class AssetType(str, Enum):
    ANNUITY = "Annuity"
    AUTOMOBILE = "Automobile"
    BOAT = "Boat"
    BOND = "Bond"
    BORROWER_ESTIMATED_TOTAL_ASSETS = "BorrowerEstimatedTotalAssets"
    BORROWER_PRIMARY_HOME = "BorrowerPrimaryHome"
    BRIDGE_LOAN_NOT_DEPOSITED = "BridgeLoanNotDeposited"
    CASH_ON_HAND = "CashOnHand"
    CERTIFICATE_OF_DEPOSIT_TIME_DEPOSIT = "CertificateOfDepositTimeDeposit"
    CHECKING_ACCOUNT = "CheckingAccount"
    EARNEST_MONEY_CASH_DEPOSIT_TOWARD_PURCHASE = "EarnestMoneyCashDepositTowardPurchase"
    EMPLOYER_ASSISTANCE = "EmployerAssistance"
    GIFT_OF_CASH = "GiftOfCash"
    GIFT_OF_PROPERTY_EQUITY = "GiftOfPropertyEquity"
    GIFTS_TOTAL = "GiftsTotal"
    GRANT = "Grant"
    INDIVIDUAL_DEVELOPMENT_ACCOUNT = "IndividualDevelopmentAccount"
    LIFE_INSURANCE = "LifeInsurance"
    MONEY_MARKET_FUND = "MoneyMarketFund"
    MUTUAL_FUND = "MutualFund"
    NET_WORTH_OF_BUSINESS_OWNED = "NetWorthOfBusinessOwned"
    PENDING_NET_SALE_PROCEEDS_FROM_REAL_ESTATE_ASSETS = "PendingNetSaleProceedsFromRealEstateAssets"  # noqa: B950
    PROCEEDS_FROM_SALE_OF_NON_REAL_ESTATE_ASSET = "ProceedsFromSaleOfNonRealEstateAsset"
    PROCEEDS_FROM_SECURED_LOAN = "ProceedsFromSecuredLoan"
    PROCEEDS_FROM_UNSECURED_LOAN = "ProceedsFromUnsecuredLoan"
    REAL_ESTATE_OWNED = "RealEstateOwned"
    RECREATIONAL_VEHICLE = "RecreationalVehicle"
    RELOCATION_MONEY = "RelocationMoney"
    RETIREMENT_FUND = "RetirementFund"
    SALE_OTHER_ASSETS = "SaleOtherAssets"
    SAVINGS_ACCOUNT = "SavingsAccount"
    SAVINGS_BOND = "SavingsBond"
    SEVERANCE_PACKAGE = "SeverancePackage"
    STOCK = "Stock"
    STOCK_OPTIONS = "StockOptions"
    TRUST_ACCOUNT = "TrustAccount"
