version: 2.1

workflows:
  partner_profile_run:
    when: << pipeline.parameters.run-partner_profile >>
    jobs:
      - app_testing:
          appName   : "partner_profile"
          context:
            - dshah-aws-user-creds
      - app_builder:
          target-env: "dshah"
          appName   : "partner_profile"
          context: 
            - cicd-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - app_testing
      - app_starter:
          target-env: "dshah"
          appName   : "partner-profile"
          directory : "partner_profile"
          context: 
            - dshah-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - app_builder