version: 2.1

workflows:
  partner_profile_PR:
    when: 
      and:
        - equal: [ true, << pipeline.parameters.run-partner_profile >> ]
        - equal: [ false, << pipeline.parameters.api_call>> ]
        - not:
            equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - py_app_testing:
          appName   : "partner_profile"
          context:
            - dshah-aws-user-creds
            - cicd-platform-slack-creds

  partner_profile:
    when: 
      and:
        - equal: [ true, << pipeline.parameters.run-partner_profile >> ]
        - equal: [ main, << pipeline.git.branch >> ]
        - equal: [ false, << pipeline.parameters.api_call>> ]
    jobs:
      - py_app_testing:
          name: app-tester-partner_profile
          appName   : "partner_profile"
          context:
            - dshah-aws-user-creds
            - cicd-platform-slack-creds
      - app_builder:
          name: app-builder-partner_profile
          target-env: "dshah"
          appName   : "partner_profile"
          context: 
            - cicd-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - app-tester-partner_profile
      - app_starter:
          name: app-starter-partner_profile-dshah
          target-env: "dshah"
          appName   : "partner-profile"
          directory : "partner_profile"
          context: 
            - dshah-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - app-builder-partner_profile