version: 2.1

workflows:
  app_demo_verification_service-staging:
    when:
      and:
        - matches:
            pattern: /^[a-zA-Z0-9_]+-\d+\.\d+\.\d+-[rc\d]+$/
            value: << pipeline.parameters.version >>
        - equal: [true, << pipeline.parameters.run-app_demo_verification_service-staging >>]
        - equal: [true, << pipeline.parameters.api_call>>]
        - equal: [main, << pipeline.git.branch >>]
    jobs:
      - container_promoter:
          name: container-promoter-app_demo_verification_service-staging
          target-env: "staging"
          appName: "app-demo-verification-service"
          version: << pipeline.parameters.version >>
          context:
            - cicd-aws-user-creds
            - cicd-platform-slack-creds
      - tf-test:
          name: tf-tester-app_demo_verification_service-staging
          target-env: "staging"
          appName: "app-demo-verification-service"
          context:
            - cicd-deployer-aws-user
          requires:
            - container-promoter-app_demo_verification_service-staging
      - tf-plan:
          name: tf-plan-app_demo_verification_service-staging
          target-env: "staging"
          appName: "app-demo-verification-service"
          context:
            - cicd-deployer-aws-user
          requires:
            - tf-tester-app_demo_verification_service-staging
      - tf-apply:
          name: tf-apply-app_demo_verification_service-staging
          target-env: "staging"
          appName: "app-demo-verification-service"
          context:
            - cicd-deployer-aws-user
          requires:
            - tf-plan-app_demo_verification_service-staging
      - container_starter:
          name: container-starter-app_demo_verification_service-staging
          target-env: "staging"
          appName: "app-demo-verification-service"
          context:
            - staging-aws-user-creds
            - cicd-platform-slack-creds
          requires:
            - tf-apply-app_demo_verification_service-staging
      # - slack/on-hold:
      #     mentions: '@dow-platform'
      #     context:
      #       - cicd-platform-slack-creds
      #     requires:
      #       - app-starter-for-staging
